import {validateLesson,answered,gradeTask} from './scoring.js';
import {draftKey,newDraft,loadDraft,persist} from './storage.js';
import {buildResult,readableWork} from './results.js';
import {COLLECTOR_URL,submitResult} from './submitter.js';
import {renderers,escapeHTML as e,wordCount} from './renderers.js';

const main=document.getElementById('main'),saveStatus=document.getElementById('save-status');
let lesson,state,key,enteredAt=0,activeId=null,savingFailed=false,view='landing';
document.getElementById('theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';};
function tell(text,error=false){saveStatus.textContent=text;saveStatus.classList.toggle('error',error);}
function save(strict=false){try{persist(localStorage,key,state);savingFailed=false;tell(state.preview?'Предпросмотр · отдельный черновик на этом устройстве':'Черновик сохранён на этом устройстве');}catch(error){savingFailed=true;tell('Не удалось сохранить черновик. Не закрывайте страницу; скачайте работу на экране итога.',true);if(strict)throw error;}}
function track(){if(activeId&&enteredAt&&!document.hidden){state.duration[activeId]=(state.duration[activeId]||0)+Date.now()-enteredAt;}enteredAt=Date.now();}
function focusHeading(){main.querySelector('h1,h2')?.focus();}
function note(text){const box=document.getElementById('feedback');if(box)box.textContent=text;}
function changeAnswer(task,value){track();state.answers[task.id]=value;delete state.checked[task.id];save();document.getElementById('feedback').textContent='';}
function allText(){return (lesson.writingTaskIds||[]).map(id=>state.answers[id]||'').join('\n\n');}
function firstRevision(){
  if(state.versions.some(v=>v.kind==='first'))return true;
  if(!(lesson.writingTaskIds||[]).every(id=>String(state.answers[id]||'').trim())){note('Сначала напиши все абзацы. К ним можно вернуться через этап «Пишем».');return false;}
  state.versions.push({kind:'first',label:'Первая самостоятельная редакция',at:new Date().toISOString(),text:allText(),answers:structuredClone(state.answers),sampleViewed:!!state.samples_viewed_at});save();return true;
}
function landing(){
  view='landing';activeId=null;
  main.innerHTML=`<div class="landing"><section class="intro"><div class="eyebrow">${lesson.grade} класс / урок ${e(lesson.lesson)} / ${lesson.subject==='russian'?'русский язык':'литература'}</div><h1>${e(lesson.display.heroTitle)}<br><span class="gold">${e(lesson.display.heroAccent)}</span></h1><p class="lead">${e(lesson.title)}</p><p>${e(lesson.display.description)}</p><div class="pills">${lesson.display.pills.map(p=>`<span class="pill">${e(p)}</span>`).join('')}</div></section><section class="start-card"><div class="eyebrow">ТВОЯ МАСТЕРСКАЯ</div><h2 style="margin:14px 0 22px">Начнём с главного</h2><form id="start-form"><div class="form-row"><label>Фамилия, имя<input id="student" required maxlength="150" autocomplete="name" placeholder="Как тебя зовут?"></label><label>Класс<input id="klass" required maxlength="30" value="${lesson.grade}" autocomplete="off"></label></div><button class="primary" type="submit">Начать или продолжить →</button></form><button id="preview" class="quiet">Посмотреть без имени</button><p class="small" style="margin:18px 0 0">Ответы сохраняются в этом браузере отдельно для каждого имени и класса. На общем устройстве начни работу под своим именем.</p><p id="start-error" role="alert"></p></section></div><div class="journey">${lesson.display.journey.map((item,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><strong>${e(item.title)}</strong><br><span>${e(item.description)}</span></div>`).join('')}</div><p class="small assignment-note">${e(lesson.pacing)} Подготовка оценивается отдельно от самостоятельного текста. Это учебная диагностика, не шкала ОГЭ.</p>`;
  document.getElementById('start-form').onsubmit=event=>{event.preventDefault();start(false);};document.getElementById('preview').onclick=()=>start(true);
}
function start(preview){
  const student=preview?'Предпросмотр':document.getElementById('student').value.trim();const klass=preview?lesson.grade+' класс':document.getElementById('klass').value.trim();
  if(!student||!klass){document.getElementById('start-error').textContent='Укажи имя и класс.';return;}
  key=draftKey(lesson,student,klass,preview);
  try{state=loadDraft(localStorage,key,lesson)||newDraft(lesson,student,klass,preview);}catch(error){document.getElementById('start-error').textContent='Не удалось открыть хранилище или прочитать черновик. Существующие ответы не перезаписаны. Проверь разрешение браузера на сохранение данных.';return;}
  state.index=Math.min(Math.max(0,state.index||0),lesson.tasks.length-1);save();if(state.pending)showResult();else renderTask();
}
function source(){return `<details class="source" ${matchMedia('(min-width:761px)').matches?'open':''}><summary>Исходный текст <span class="small">· ${lesson.material.paragraphs.length} абзаца</span></summary>${lesson.material.paragraphs.map((p,i)=>`<div class="source-part"><small>АБЗАЦ ${i+1}</small><p>${e(p)}</p></div>`).join('')}<cite>${e(lesson.material.attribution)}</cite><p><a href="${e(lesson.material.sourceUrl)}" target="_blank" rel="noopener">Рабочий лист урока ↗</a></p></details>`;}
function shell(stage){const done=lesson.tasks.filter(t=>!t.optional&&answered(t,state.answers[t.id])).length,total=lesson.tasks.filter(t=>!t.optional).length;return `<div class="workspace-head"><div><div class="eyebrow">МАСТЕРСКАЯ ИЗЛОЖЕНИЯ · УРОК ${lesson.lesson}</div><h1 tabindex="-1">${e(lesson.display.shortTitle||lesson.title)}</h1></div><div><span class="${state.preview?'preview-tag':'small'}">${e(state.student)} · ${e(state.class)}</span><br><button id="switch-profile" class="quiet" style="font-size:13px">Сменить ученика</button></div></div><div class="row-spread"><span class="small">Заполнено ${done} из ${total} обязательных заданий</span><span class="small">Можно возвращаться и уточнять ответы</span></div><div class="progress-track" role="progressbar" aria-label="Заполненные задания" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${done}"><span style="width:${done/total*100}%"></span></div><nav class="steps" aria-label="Этапы работы">${lesson.stages.map((s,i)=>`<button data-stage="${e(s.id)}" ${s.id===stage?'aria-current="step"':''}>${i+1}. ${e(s.title)}</button>`).join('')}<button id="review">Итог</button></nav>`;}
function bindShell(){document.getElementById('switch-profile').onclick=()=>{track();save();landing();};document.querySelectorAll('[data-stage]').forEach(button=>button.onclick=()=>go(lesson.tasks.findIndex(t=>t.stage===button.dataset.stage)));document.getElementById('review').onclick=review;}
function go(index){track();state.index=index;save();renderTask();focusHeading();}
function renderTask(){
  view='task';const task=lesson.tasks[state.index];activeId=task.id;enteredAt=Date.now();
  main.innerHTML=shell(task.stage)+`<div class="work-grid ${task.showFullText?'full-text':''}"><section class="panel"><div class="row-spread"><span class="eyebrow">${task.optional?'ДОПОЛНИТЕЛЬНО':'ЗАДАНИЕ '+(state.index+1)+' ИЗ '+lesson.tasks.filter(t=>!t.optional).length}</span><span class="badge">${task.type==='open-response'?'Своими словами':task.points+' '+(task.points===1?'балл':'баллов')}</span></div><h2 class="task-heading" tabindex="-1">${e(task.prompt)}</h2>${task.context?`<p>${e(task.context)}</p>`:''}${task.showFullText?`<section class="inline-source" aria-labelledby="reference-title"><h3 id="reference-title">${e(task.referenceTitle||'Исходный текст')}</h3>${lesson.material.paragraphs.map((p,i)=>`<p><strong>${i+1}.</strong> ${e(p)}</p>`).join('')}<p class="small">${e(lesson.material.attribution)}</p></section>`:''}${task.paragraph?`<blockquote class="task-quote">${e(lesson.material.paragraphs[task.paragraph-1])}</blockquote>`:''}${task.before?`<div class="pair"><div><span class="eyebrow">БЫЛО · АБЗАЦ ${e(task.sourceParagraph)}</span><p>${e(task.before)}</p></div><div><span class="eyebrow">СТАЛО</span><p>${e(task.after)}</p></div></div>`:''}<div id="task-tools"></div><div id="answer-slot"></div>${task.rubric?`<details class="rubric"><summary>На что обратить внимание</summary><ul>${task.rubric.map(r=>`<li>${e(r)}</li>`).join('')}</ul></details>`:''}<div id="question-actions" class="question-actions"></div><div id="feedback" class="feedback" role="status" aria-live="polite"></div><div id="hint"></div><div class="nav-bottom"><button id="prev" ${state.index===0?'disabled':''}>← Назад</button><button id="next" class="primary">${state.index===lesson.tasks.length-1?'К итогу':'Далее →'}</button></div></section>${source()}</div>`;
  document.getElementById('answer-slot').append(renderers[task.type](task,state.answers[task.id],value=>changeAnswer(task,value)));
  const actions=document.getElementById('question-actions');
  if(lesson.mode==='practice'){
    if(task.type!=='open-response'){const button=document.createElement('button');button.textContent='Проверить';button.id='check';button.onclick=()=>{if(!answered(task,state.answers[task.id])){note('Сначала дай ответ.');return;}state.attempts[task.id]=(state.attempts[task.id]||0)+1;state.checked[task.id]=true;save();feedback(task);};actions.append(button);}
    if(task.hint){const button=document.createElement('button');button.textContent='Подсказка';button.onclick=()=>{state.hint_used[task.id]=true;state.hint_history=state.hint_history||[];state.hint_history.push({task_id:task.id,at:new Date().toISOString()});save();document.getElementById('hint').innerHTML=`<p class="hint">${e(task.hint)}</p>`;};actions.append(button);}
  }
  if(state.checked[task.id]&&lesson.mode==='practice')feedback(task);
  if(state.hint_used[task.id]&&lesson.mode==='practice')document.getElementById('hint').innerHTML=`<p class="hint">${e(task.hint)}</p>`;
  if(task.composeFrom){document.getElementById('task-tools').innerHTML='<button id="assemble" class="quiet">Собрать из моих абзацев</button><p class="word-note">Кнопка переносит твои абзацы в поле редактуры. Первая редакция хранится отдельно.</p>';document.getElementById('assemble').onclick=()=>{if(state.answers[task.id]&&!confirm('Заменить текущий текст редактуры твоими абзацами?'))return;if(!firstRevision())return;state.answers[task.id]=task.composeFrom.map(id=>state.answers[id]||'').join('\n\n');save();renderTask();};}
  if(task.sampleAfterDraft&&lesson.mode==='practice'){
    const button=document.createElement('button');button.id='sample';button.textContent='Сохранить первую редакцию и сверить';button.onclick=()=>{if(!firstRevision())return;state.samples_viewed_at=state.samples_viewed_at||new Date().toISOString();save();document.getElementById('hint').innerHTML=`<div class="hint"><strong>Один из возможных вариантов</strong>${lesson.material.samples.map(p=>`<p style="margin-top:14px">${e(p)}</p>`).join('')}<p class="small">Точное совпадение не требуется. Сравни смысл и связь мыслей, затем улучши свой текст.</p></div>`;};actions.append(button);
  }
  if(task.checklist){const list=document.createElement('div');list.className='checklist';list.innerHTML='<h3>Проверь себя</h3>'+lesson.checklist.map((label,i)=>`<label class="option"><input type="checkbox" value="${i}" ${state.checklist.includes(i)?'checked':''}><span>${e(label)}</span></label>`).join('');list.onchange=()=>{state.checklist=[...list.querySelectorAll(':checked')].map(el=>Number(el.value));save();};document.getElementById('answer-slot').after(list);}
  bindShell();document.getElementById('prev').onclick=()=>go(state.index-1);document.getElementById('next').onclick=()=>state.index===lesson.tasks.length-1?review():go(state.index+1);
}
function feedback(task){const grade=gradeTask(task,state.answers[task.id]);note((grade.correct?'✓ Верно. ':'Пока нет. ')+(task.explanation||''));}
function review(){track();activeId=null;view='review';save();const missing=lesson.tasks.filter(t=>!t.optional&&!answered(t,state.answers[t.id]));main.innerHTML=shell('review')+`<section class="panel"><div class="eyebrow">ПЕРЕД ЗАВЕРШЕНИЕМ</div><h2 tabindex="-1">Посмотри на работу целиком</h2><p>${missing.length?'Не заполнено обязательных заданий: '+missing.length+'. Можно вернуться к ним или сохранить неполную работу.':'Все обязательные задания заполнены. Осталось сохранить результат.'}</p><div class="paper">${e(state.answers[lesson.finalTaskId]||allText()||'Текст ещё не написан.')}</div><details ${missing.length?'open':''}><summary>Проверка заполненности</summary><ul class="review-list">${lesson.tasks.map((t,i)=>`<li><span>${answered(t,state.answers[t.id])?'✓':'○'} ${e(t.prompt)}${t.optional?' (по желанию)':''}</span><button data-task="${i}">Открыть</button></li>`).join('')}</ul></details><p class="small">${e(lesson.display.scoreNote)}</p><div class="actions"><button id="return">Продолжить работу</button><button id="finish" class="primary">${missing.length?'Сохранить неполную работу':'Завершить и сохранить'}</button></div></section>`;bindShell();document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>go(Number(b.dataset.task)));document.getElementById('return').onclick=renderTask;document.getElementById('finish').onclick=finish;focusHeading();}
function finish(){
  if(!state.versions.some(v=>v.kind==='first'))state.versions.push({kind:'first',label:'Первая редакция',at:new Date().toISOString(),text:allText(),answers:structuredClone(state.answers),sampleViewed:!!state.samples_viewed_at});
  state.versions.push({kind:'final',label:'Редакция при завершении',at:new Date().toISOString(),text:state.answers[lesson.finalTaskId]||allText(),answers:structuredClone(state.answers),sampleViewed:!!state.samples_viewed_at});
  for(const task of lesson.tasks)if(task.type!=='open-response'&&answered(task,state.answers[task.id])&&!state.checked[task.id])state.attempts[task.id]=(state.attempts[task.id]||0)+1;
  state.pending=buildResult(lesson,state);state.receipt=null;save();showResult();
}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function showResult(){
  view='result';activeId=null;const result=state.pending,accepted=state.receipt?.trainerGrading;
  const auto=accepted?.automatic||{earned:result.auto_score,max:result.auto_max};
  const manual=accepted?.manualGroups?.[0];
  main.innerHTML=`<div class="eyebrow">${state.preview?'ПРЕДПРОСМОТР · ':' '}РЕЗУЛЬТАТ РАБОТЫ</div><h1 tabindex="-1" style="margin-top:16px">${e(lesson.display.completionTitle)}</h1><p>${e(state.student)} · ${e(state.class)}. ${savingFailed?'Скачай работу: сохранение в браузере недоступно.':'Работа сохранена на этом устройстве.'}</p><div class="score-grid"><section class="summary-card"><div class="eyebrow">ПОДГОТОВКА</div><div class="score-big">${auto.earned} <small>/ ${auto.max}</small></div><p>${e(lesson.display.automaticDescription)}</p><p class="small">Это результат тренировки, а не отметка за изложение.</p></section><section class="summary-card"><div class="eyebrow">САМОСТОЯТЕЛЬНЫЙ ТЕКСТ</div><h2 style="margin:16px 0">${manual?.earned!=null?manual.earned+' / '+manual.max:'Проверяет учитель'}</h2><p>${lesson.manualGroups[0].criteria.length} отдельных критериев: ${e(lesson.manualGroups[0].title.toLowerCase())}. ${manual?.earned!=null?'Проверено учителем.':'Балл пока не выставлен.'}</p><details class="rubric"><summary>Критерии проверки</summary><ol>${lesson.manualGroups[0].criteria.map(c=>`<li>${e(c.text)} — 1 балл</li>`).join('')}</ol></details></section></div><section class="panel"><h2>Твоя редакция</h2><div class="paper">${e(state.answers[lesson.finalTaskId]||allText()||'Нет текста.')}</div><p class="small">${wordCount(state.answers[lesson.finalTaskId]||allText())} слов. Объём служит ориентиром и не ограничивает ответ.</p><div class="drafts">${state.versions.map(v=>`<details class="version"><summary>${e(v.label)} · ${new Date(v.at).toLocaleString('ru-RU')}</summary><div class="paper">${e(v.text||'Нет текста.')}</div></details>`).join('')}</div><p class="small">${state.samples_viewed_at?'Просмотр образца отмечен в истории работы.':'Образец не просматривался.'}</p><div class="actions"><button id="download" class="primary">Скачать работу</button><button id="print">Печать</button><button id="edit" ${!state.preview&&COLLECTOR_URL&&state.transportStarted&&!state.receipt?'disabled':''}>Доработать</button><button id="switch-profile">Сменить ученика</button></div><div class="warning" id="delivery-status" role="status">${state.preview?'Это предпросмотр. Он не попадает в журнал учеников.':state.receipt?'Работа отправлена учителю. Сохранение в кабинете подтверждено.':COLLECTOR_URL?'Работа ещё не отправлена учителю.':'Отправка в кабинет для этого тренажёра пока недоступна. Скачай работу, чтобы передать её учителю.'}</div>${COLLECTOR_URL&&!state.preview?'<button id="send">Отправить учителю</button>':''}</section>`;
  document.getElementById('download').onclick=()=>download(readableWork(lesson,state,result),lesson.id+'-work.txt');document.getElementById('print').onclick=()=>window.print();document.getElementById('switch-profile').onclick=landing;
  document.getElementById('edit').onclick=()=>{state.deliveries=state.deliveries||[];state.deliveries.push({payload:state.pending,receipt:state.receipt});state.pending=null;state.receipt=null;state.transportStarted=false;save();renderTask();};
  document.getElementById('send')?.addEventListener('click',async event=>{const button=event.target;button.disabled=true;document.getElementById('edit').disabled=true;document.getElementById('switch-profile').disabled=true;try{await submitResult(COLLECTOR_URL,state,()=>save(true));showResult();}catch(error){document.getElementById('delivery-status').textContent=error.message;}finally{button.disabled=false;document.getElementById('switch-profile').disabled=false;document.getElementById('edit').disabled=!!state.transportStarted&&!state.receipt;}});focusHeading();
}
document.addEventListener('visibilitychange',()=>{if(!state||!activeId)return;if(document.hidden){state.duration[activeId]=(state.duration[activeId]||0)+Date.now()-enteredAt;enteredAt=0;save();}else enteredAt=Date.now();});
window.addEventListener('pagehide',()=>{if(state){track();save();}});
try{
  const params=new URLSearchParams(location.search),subject=params.get('subject')||'russian',grade=params.get('grade')||'9',number=params.get('lesson')||'13';
  if(!['russian','literature'].includes(subject)||!/^([5-9]|10|11)$/.test(grade)||!/^\d{1,3}$/.test(number))throw new Error('Проверь ссылку: предмет, класс или номер урока указаны неверно.');
  const response=await fetch(`data/${subject}/${grade}/lesson-${number.padStart(3,'0')}.json`);if(!response.ok)throw new Error('Этот урок пока не добавлен. Проверь номер в ссылке.');
  lesson=validateLesson(await response.json());
  if(lesson.mode==='control')throw new Error('Контрольный режим ещё не подключён к серверной проверке. Открой тренировочный комплект.');
  document.title=lesson.title+' · Кодислово';document.querySelector('.top-actions .eyebrow').textContent=(lesson.subject==='russian'?'Русский язык':'Литература')+' · '+lesson.grade+' класс';landing();
}catch(error){main.innerHTML=`<section class="panel"><h1>Не удалось открыть урок</h1><p>${e(error.message)}</p><a href="play.html?subject=russian&grade=9&lesson=13">Открыть «Пушкин и Пущин»</a></section>`;}
